apiVersion: v1
kind: Pod
metadata:
  name: multicon-volume
  labels: 
   env: prod
   app: os
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash","-c"]
    args: ["sleep 3600"]
    volumeMounts:
    - name: share
      mountPath: /data

  - name: nginx
    image: nginx
    volumeMounts:
    - name: share
      mountPath: /data

  volumes:
  - name: share
    emptyDir: {}       
     

