apiVersion: v1
kind: Pod
metadata:
 name: hostpath-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: hostpath
      mountPath: /data
  
  volumes:
  - name: hostpath
    hostPath:
     path: /data