apiVersion: v1
kind: Pod
metadata:
  name:  envpod
spec:
  containers:
  - name: app
    image: nginx
    env:
      - name: APP_NAME
        value: "env-demo"
      - name: APP_ENV
        value: "dev"
    command: ["sh", "-c", "sleep 3600"]

